App.prototype.tutorialsShowIntroduction = function( params, controller ) {

  var a = this.a;
  var x = this.x;

  return [
    a.p( x.md( "To use Ax, call the `ax()` function in a script on your page." ) ),
    a.p( [
      "Click ", x.fa("play"), " to run the example code in an iframe. ",
      a.ul( [
        a.li( [ "Click ", x.fa("code"), " to see the result HTML." ] ),
        a.li( [ "Click ᴥ to see the Cell object generated by Ax (with any functions serialized for presentation)." ] ),
      ] ),
    ] ),
    this.coderunner( `ax( "Hello world" );` ),
  ];
};
