App.prototype.guideShowIntroduction = function( params, controller ) {

  var a = this.a;
  var x = this.x;

  return [
    x.md ( [
      "You would normally call `ax()` in a script on your page.",
      "In this guide you can test the example code by clicking **Run**. The result will be shown in an iframe."
    ] ),
    a.p( [
      a.ul( [
        a.li( [ "Click ", x.icon( "fa fa-flag-o" ), " to see the initial HTML." ] ),
        a.li( [ "Click ", x.icon( "fa fa-flag-checkered" ), " to see the final HTML. This is useful for dynamic content, where the HTML has changed." ] ),
        a.li( [ x.md( "Click ᴥ to see the Cell object generated by `ax()` (with any functions serialized for presentation).", { inline: true } ) ] ),
      ] ),
    ] ),
    this.coderunner( `ax( "Hello world" );` ),
    x.md ( [
      `\`ax()\` uses <a href='https://github.com/intercellular/cell' target="celljs">Cell</a> to give a DOM element an encapsulated execution context, with its own data and functions`,
      `\`ax()\` is essentially a set of helpers and libraries that output Cell objects.`
    ], { tag: { class: "detail-box" } } )

  ];
};
